/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IERC223Receiver } from "../IERC223Receiver";

export class IERC223Receiver__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC223Receiver {
    return new Contract(address, _abi, signerOrProvider) as IERC223Receiver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "tokenFallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
