/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ModuleERC165 } from "../ModuleERC165";

export class ModuleERC165__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ModuleERC165 {
    return new Contract(address, _abi, signerOrProvider) as ModuleERC165;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
