/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ERC165CheckerMockInterface extends ethers.utils.Interface {
  functions: {
    "doesContractImplementInterface(address,bytes4)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "doesContractImplementInterface",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "doesContractImplementInterface",
    data: BytesLike
  ): Result;

  events: {};
}

export class ERC165CheckerMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ERC165CheckerMockInterface;

  functions: {
    doesContractImplementInterface(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "doesContractImplementInterface(address,bytes4)"(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  doesContractImplementInterface(
    _contract: string,
    _interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "doesContractImplementInterface(address,bytes4)"(
    _contract: string,
    _interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    doesContractImplementInterface(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "doesContractImplementInterface(address,bytes4)"(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    doesContractImplementInterface(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "doesContractImplementInterface(address,bytes4)"(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    doesContractImplementInterface(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "doesContractImplementInterface(address,bytes4)"(
      _contract: string,
      _interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
