/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface FactoryInterface extends Interface {
  functions: {
    deploy: TypedFunctionDescription<{
      encode([_code, _salt]: [Arrayish, Arrayish]): string;
    }>;
  };

  events: {};
}

export class Factory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Factory;
  attach(addressOrName: string): Factory;
  deployed(): Promise<Factory>;

  on(event: EventFilter | string, listener: Listener): Factory;
  once(event: EventFilter | string, listener: Listener): Factory;
  addListener(eventName: EventFilter | string, listener: Listener): Factory;
  removeAllListeners(eventName: EventFilter | string): Factory;
  removeListener(eventName: any, listener: Listener): Factory;

  interface: FactoryInterface;

  functions: {
    deploy(
      _code: Arrayish,
      _salt: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  deploy(
    _code: Arrayish,
    _salt: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    deploy(_code: Arrayish, _salt: Arrayish): Promise<BigNumber>;
  };
}
