/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GasBurnerMockInterface extends ethers.utils.Interface {
  functions: {
    "burnGas(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burnGas",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burnGas", data: BytesLike): Result;

  events: {
    "ProvidedGas(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProvidedGas"): EventFragment;
}

export class GasBurnerMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GasBurnerMockInterface;

  functions: {
    burnGas(
      _burn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burnGas(uint256)"(
      _burn: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  burnGas(
    _burn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burnGas(uint256)"(
    _burn: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    burnGas(_burn: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "burnGas(uint256)"(
      _burn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ProvidedGas(_val: null): EventFilter;
  };

  estimateGas: {
    burnGas(_burn: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "burnGas(uint256)"(
      _burn: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnGas(
      _burn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burnGas(uint256)"(
      _burn: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
