/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface HookMockInterface extends Interface {
  functions: {
    onHookMockCall: TypedFunctionDescription<{
      encode([_num]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class HookMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): HookMock;
  attach(addressOrName: string): HookMock;
  deployed(): Promise<HookMock>;

  on(event: EventFilter | string, listener: Listener): HookMock;
  once(event: EventFilter | string, listener: Listener): HookMock;
  addListener(eventName: EventFilter | string, listener: Listener): HookMock;
  removeAllListeners(eventName: EventFilter | string): HookMock;
  removeListener(eventName: any, listener: Listener): HookMock;

  interface: HookMockInterface;

  functions: {
    onHookMockCall(_num: BigNumberish): Promise<BigNumber>;
  };

  onHookMockCall(_num: BigNumberish): Promise<BigNumber>;

  filters: {};

  estimate: {
    onHookMockCall(_num: BigNumberish): Promise<BigNumber>;
  };
}
