/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface HookCallerMockInterface extends Interface {
  functions: {
    callERC1155Received: TypedFunctionDescription<{
      encode([_addr]: [string]): string;
    }>;

    callERC1155BatchReceived: TypedFunctionDescription<{
      encode([_addr]: [string]): string;
    }>;

    callERC721Received: TypedFunctionDescription<{
      encode([_addr]: [string]): string;
    }>;

    callERC223Received: TypedFunctionDescription<{
      encode([_addr]: [string]): string;
    }>;
  };

  events: {};
}

export class HookCallerMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): HookCallerMock;
  attach(addressOrName: string): HookCallerMock;
  deployed(): Promise<HookCallerMock>;

  on(event: EventFilter | string, listener: Listener): HookCallerMock;
  once(event: EventFilter | string, listener: Listener): HookCallerMock;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): HookCallerMock;
  removeAllListeners(eventName: EventFilter | string): HookCallerMock;
  removeListener(eventName: any, listener: Listener): HookCallerMock;

  interface: HookCallerMockInterface;

  functions: {
    callERC1155Received(
      _addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    callERC1155BatchReceived(
      _addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    callERC721Received(
      _addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    callERC223Received(
      _addr: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  callERC1155Received(
    _addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  callERC1155BatchReceived(
    _addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  callERC721Received(
    _addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  callERC223Received(
    _addr: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    callERC1155Received(_addr: string): Promise<BigNumber>;

    callERC1155BatchReceived(_addr: string): Promise<BigNumber>;

    callERC721Received(_addr: string): Promise<BigNumber>;

    callERC223Received(_addr: string): Promise<BigNumber>;
  };
}
