/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IERC721ReceiverInterface extends Interface {
  functions: {
    onERC721Received: TypedFunctionDescription<{
      encode([, , ,]: [string, string, BigNumberish, Arrayish]): string;
    }>;
  };

  events: {};
}

export class IERC721Receiver extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IERC721Receiver;
  attach(addressOrName: string): IERC721Receiver;
  deployed(): Promise<IERC721Receiver>;

  on(event: EventFilter | string, listener: Listener): IERC721Receiver;
  once(event: EventFilter | string, listener: Listener): IERC721Receiver;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IERC721Receiver;
  removeAllListeners(eventName: EventFilter | string): IERC721Receiver;
  removeListener(eventName: any, listener: Listener): IERC721Receiver;

  interface: IERC721ReceiverInterface;

  functions: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: Arrayish
    ): Promise<BigNumber>;
  };
}
