/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IModuleUpdateInterface extends Interface {
  functions: {
    updateImplementation: TypedFunctionDescription<{
      encode([_implementation]: [string]): string;
    }>;
  };

  events: {};
}

export class IModuleUpdate extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IModuleUpdate;
  attach(addressOrName: string): IModuleUpdate;
  deployed(): Promise<IModuleUpdate>;

  on(event: EventFilter | string, listener: Listener): IModuleUpdate;
  once(event: EventFilter | string, listener: Listener): IModuleUpdate;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IModuleUpdate;
  removeAllListeners(eventName: EventFilter | string): IModuleUpdate;
  removeListener(eventName: any, listener: Listener): IModuleUpdate;

  interface: IModuleUpdateInterface;

  functions: {
    updateImplementation(
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  updateImplementation(
    _implementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    updateImplementation(_implementation: string): Promise<BigNumber>;
  };
}
