/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IModuleCreatorInterface extends Interface {
  functions: {
    createContract: TypedFunctionDescription<{
      encode([_code]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class IModuleCreator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IModuleCreator;
  attach(addressOrName: string): IModuleCreator;
  deployed(): Promise<IModuleCreator>;

  on(event: EventFilter | string, listener: Listener): IModuleCreator;
  once(event: EventFilter | string, listener: Listener): IModuleCreator;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IModuleCreator;
  removeAllListeners(eventName: EventFilter | string): IModuleCreator;
  removeListener(eventName: any, listener: Listener): IModuleCreator;

  interface: IModuleCreatorInterface;

  functions: {
    createContract(
      _code: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  createContract(
    _code: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    createContract(_code: Arrayish): Promise<BigNumber>;
  };
}
