/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ModuleAuthHardInterface extends Interface {
  functions: {
    FACTORY: TypedFunctionDescription<{ encode([]: []): string }>;

    INIT_CODE_HASH: TypedFunctionDescription<{ encode([]: []): string }>;

    isValidSignature: TypedFunctionDescription<{
      encode([_hash, _signatures]: [Arrayish, Arrayish]): string;
    }>;

    recoverSigner: TypedFunctionDescription<{
      encode([_hash, _signature]: [Arrayish, Arrayish]): string;
    }>;
  };

  events: {};
}

export class ModuleAuthHard extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ModuleAuthHard;
  attach(addressOrName: string): ModuleAuthHard;
  deployed(): Promise<ModuleAuthHard>;

  on(event: EventFilter | string, listener: Listener): ModuleAuthHard;
  once(event: EventFilter | string, listener: Listener): ModuleAuthHard;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ModuleAuthHard;
  removeAllListeners(eventName: EventFilter | string): ModuleAuthHard;
  removeListener(eventName: any, listener: Listener): ModuleAuthHard;

  interface: ModuleAuthHardInterface;

  functions: {
    FACTORY(): Promise<string>;

    INIT_CODE_HASH(): Promise<string>;

    isValidSignature(_hash: Arrayish, _signatures: Arrayish): Promise<string>;

    recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<string>;
  };

  FACTORY(): Promise<string>;

  INIT_CODE_HASH(): Promise<string>;

  isValidSignature(_hash: Arrayish, _signatures: Arrayish): Promise<string>;

  recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<string>;

  filters: {};

  estimate: {
    FACTORY(): Promise<BigNumber>;

    INIT_CODE_HASH(): Promise<BigNumber>;

    isValidSignature(
      _hash: Arrayish,
      _signatures: Arrayish
    ): Promise<BigNumber>;

    recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<BigNumber>;
  };
}
