/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ModuleMockInterface extends ethers.utils.Interface {
  functions: {
    "ping()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ping", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;

  events: {
    "Pong()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Pong"): EventFragment;
}

export class ModuleMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ModuleMockInterface;

  functions: {
    ping(overrides?: Overrides): Promise<ContractTransaction>;

    "ping()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  ping(overrides?: Overrides): Promise<ContractTransaction>;

  "ping()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    ping(overrides?: CallOverrides): Promise<void>;

    "ping()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    Pong(): EventFilter;
  };

  estimateGas: {
    ping(overrides?: Overrides): Promise<BigNumber>;

    "ping()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ping(overrides?: Overrides): Promise<PopulatedTransaction>;

    "ping()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
