/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ModuleERC165Interface extends Interface {
  functions: {
    supportsInterface: TypedFunctionDescription<{
      encode([_interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class ModuleERC165 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ModuleERC165;
  attach(addressOrName: string): ModuleERC165;
  deployed(): Promise<ModuleERC165>;

  on(event: EventFilter | string, listener: Listener): ModuleERC165;
  once(event: EventFilter | string, listener: Listener): ModuleERC165;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ModuleERC165;
  removeAllListeners(eventName: EventFilter | string): ModuleERC165;
  removeListener(eventName: any, listener: Listener): ModuleERC165;

  interface: ModuleERC165Interface;

  functions: {
    supportsInterface(_interfaceID: Arrayish): Promise<boolean>;
  };

  supportsInterface(_interfaceID: Arrayish): Promise<boolean>;

  filters: {};

  estimate: {
    supportsInterface(_interfaceID: Arrayish): Promise<BigNumber>;
  };
}
