/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ModuleAuthInterface extends Interface {
  functions: {
    isValidSignature: TypedFunctionDescription<{
      encode([_hash, _signatures]: [Arrayish, Arrayish]): string;
    }>;

    supportsInterface: TypedFunctionDescription<{
      encode([_interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {};
}

export class ModuleAuth extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ModuleAuth;
  attach(addressOrName: string): ModuleAuth;
  deployed(): Promise<ModuleAuth>;

  on(event: EventFilter | string, listener: Listener): ModuleAuth;
  once(event: EventFilter | string, listener: Listener): ModuleAuth;
  addListener(eventName: EventFilter | string, listener: Listener): ModuleAuth;
  removeAllListeners(eventName: EventFilter | string): ModuleAuth;
  removeListener(eventName: any, listener: Listener): ModuleAuth;

  interface: ModuleAuthInterface;

  functions: {
    isValidSignature(_hash: Arrayish, _signatures: Arrayish): Promise<string>;

    supportsInterface(_interfaceID: Arrayish): Promise<boolean>;
  };

  isValidSignature(_hash: Arrayish, _signatures: Arrayish): Promise<string>;

  supportsInterface(_interfaceID: Arrayish): Promise<boolean>;

  filters: {};

  estimate: {
    isValidSignature(
      _hash: Arrayish,
      _signatures: Arrayish
    ): Promise<BigNumber>;

    supportsInterface(_interfaceID: Arrayish): Promise<BigNumber>;
  };
}
