/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ModuleCallsInterface extends Interface {
  functions: {
    FACTORY: TypedFunctionDescription<{ encode([]: []): string }>;

    INIT_CODE_HASH: TypedFunctionDescription<{ encode([]: []): string }>;

    isValidSignature: TypedFunctionDescription<{
      encode([_hash, _signature]: [Arrayish, Arrayish]): string;
    }>;

    nonce: TypedFunctionDescription<{ encode([]: []): string }>;

    recoverSigner: TypedFunctionDescription<{
      encode([_hash, _signature]: [Arrayish, Arrayish]): string;
    }>;

    execute: TypedFunctionDescription<{
      encode([_txs, _nonce, _signature]: [
        {
          delegateCall: boolean;
          skipOnError: boolean;
          target: string;
          value: BigNumberish;
          data: Arrayish;
        }[],
        BigNumberish,
        Arrayish
      ]): string;
    }>;
  };

  events: {
    NonceChange: TypedEventDescription<{
      encodeTopics([newNonce]: [null]): string[];
    }>;

    TxFailed: TypedEventDescription<{
      encodeTopics([_index, _reason]: [null, null]): string[];
    }>;
  };
}

export class ModuleCalls extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ModuleCalls;
  attach(addressOrName: string): ModuleCalls;
  deployed(): Promise<ModuleCalls>;

  on(event: EventFilter | string, listener: Listener): ModuleCalls;
  once(event: EventFilter | string, listener: Listener): ModuleCalls;
  addListener(eventName: EventFilter | string, listener: Listener): ModuleCalls;
  removeAllListeners(eventName: EventFilter | string): ModuleCalls;
  removeListener(eventName: any, listener: Listener): ModuleCalls;

  interface: ModuleCallsInterface;

  functions: {
    FACTORY(): Promise<string>;

    INIT_CODE_HASH(): Promise<string>;

    isValidSignature(_hash: Arrayish, _signature: Arrayish): Promise<string>;

    nonce(): Promise<BigNumber>;

    recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<string>;

    execute(
      _txs: {
        delegateCall: boolean;
        skipOnError: boolean;
        target: string;
        value: BigNumberish;
        data: Arrayish;
      }[],
      _nonce: BigNumberish,
      _signature: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  FACTORY(): Promise<string>;

  INIT_CODE_HASH(): Promise<string>;

  isValidSignature(_hash: Arrayish, _signature: Arrayish): Promise<string>;

  nonce(): Promise<BigNumber>;

  recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<string>;

  execute(
    _txs: {
      delegateCall: boolean;
      skipOnError: boolean;
      target: string;
      value: BigNumberish;
      data: Arrayish;
    }[],
    _nonce: BigNumberish,
    _signature: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    NonceChange(newNonce: null): EventFilter;

    TxFailed(_index: null, _reason: null): EventFilter;
  };

  estimate: {
    FACTORY(): Promise<BigNumber>;

    INIT_CODE_HASH(): Promise<BigNumber>;

    isValidSignature(_hash: Arrayish, _signature: Arrayish): Promise<BigNumber>;

    nonce(): Promise<BigNumber>;

    recoverSigner(_hash: Arrayish, _signature: Arrayish): Promise<BigNumber>;

    execute(
      _txs: {
        delegateCall: boolean;
        skipOnError: boolean;
        target: string;
        value: BigNumberish;
        data: Arrayish;
      }[],
      _nonce: BigNumberish,
      _signature: Arrayish
    ): Promise<BigNumber>;
  };
}
