/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface RequireUtilsInterface extends ethers.utils.Interface {
  functions: {
    "lastSignerUpdate(address)": FunctionFragment;
    "lastWalletUpdate(address)": FunctionFragment;
    "publishConfig(address,uint256,tuple[],bool)": FunctionFragment;
    "publishInitialSigners(address,bytes32,uint256,bytes,bool)": FunctionFragment;
    "requireMinNonce(address,uint256)": FunctionFragment;
    "requireNonExpired(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "lastSignerUpdate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "lastWalletUpdate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "publishConfig",
    values: [
      string,
      BigNumberish,
      { weight: BigNumberish; signer: string }[],
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "publishInitialSigners",
    values: [string, BytesLike, BigNumberish, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "requireMinNonce",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requireNonExpired",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "lastSignerUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastWalletUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishInitialSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireMinNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireNonExpired",
    data: BytesLike
  ): Result;

  events: {
    "RequiredConfig(address,bytes32,uint256,bytes)": EventFragment;
    "RequiredSigner(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RequiredConfig"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequiredSigner"): EventFragment;
}

export class RequireUtils extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: RequireUtilsInterface;

  functions: {
    lastSignerUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "lastSignerUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastWalletUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "lastWalletUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    publishConfig(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publishConfig(address,uint256,tuple[],bool)"(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    publishInitialSigners(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "publishInitialSigners(address,bytes32,uint256,bytes,bool)"(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    requireMinNonce(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "requireMinNonce(address,uint256)"(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    requireNonExpired(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "requireNonExpired(uint256)"(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  lastSignerUpdate(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "lastSignerUpdate(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastWalletUpdate(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "lastWalletUpdate(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  publishConfig(
    _wallet: string,
    _threshold: BigNumberish,
    _members: { weight: BigNumberish; signer: string }[],
    _index: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publishConfig(address,uint256,tuple[],bool)"(
    _wallet: string,
    _threshold: BigNumberish,
    _members: { weight: BigNumberish; signer: string }[],
    _index: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  publishInitialSigners(
    _wallet: string,
    _hash: BytesLike,
    _sizeMembers: BigNumberish,
    _signature: BytesLike,
    _index: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "publishInitialSigners(address,bytes32,uint256,bytes,bool)"(
    _wallet: string,
    _hash: BytesLike,
    _sizeMembers: BigNumberish,
    _signature: BytesLike,
    _index: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  requireMinNonce(
    _wallet: string,
    _nonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "requireMinNonce(address,uint256)"(
    _wallet: string,
    _nonce: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  requireNonExpired(
    _expiration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "requireNonExpired(uint256)"(
    _expiration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    lastSignerUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lastSignerUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastWalletUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lastWalletUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishConfig(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "publishConfig(address,uint256,tuple[],bool)"(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    publishInitialSigners(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "publishInitialSigners(address,bytes32,uint256,bytes,bool)"(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    requireMinNonce(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "requireMinNonce(address,uint256)"(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    requireNonExpired(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "requireNonExpired(uint256)"(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    RequiredConfig(
      _wallet: string | null,
      _imageHash: BytesLike | null,
      _threshold: null,
      _signers: null
    ): EventFilter;

    RequiredSigner(_wallet: string | null, _signer: string | null): EventFilter;
  };

  estimateGas: {
    lastSignerUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lastSignerUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastWalletUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lastWalletUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishConfig(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publishConfig(address,uint256,tuple[],bool)"(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    publishInitialSigners(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "publishInitialSigners(address,bytes32,uint256,bytes,bool)"(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    requireMinNonce(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requireMinNonce(address,uint256)"(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requireNonExpired(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requireNonExpired(uint256)"(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    lastSignerUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lastSignerUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastWalletUpdate(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lastWalletUpdate(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publishConfig(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publishConfig(address,uint256,tuple[],bool)"(
      _wallet: string,
      _threshold: BigNumberish,
      _members: { weight: BigNumberish; signer: string }[],
      _index: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    publishInitialSigners(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "publishInitialSigners(address,bytes32,uint256,bytes,bool)"(
      _wallet: string,
      _hash: BytesLike,
      _sizeMembers: BigNumberish,
      _signature: BytesLike,
      _index: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    requireMinNonce(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "requireMinNonce(address,uint256)"(
      _wallet: string,
      _nonce: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requireNonExpired(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "requireNonExpired(uint256)"(
      _expiration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
