/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface TxnAggregatorInterface extends Interface {
  functions: {
    executeTxns: TypedFunctionDescription<{
      encode([_txns, _revert]: [
        { dest: string; data: Arrayish }[],
        boolean
      ]): string;
    }>;

    singleContract_executeTxns: TypedFunctionDescription<{
      encode([_contract, _txns, _revert]: [
        string,
        Arrayish[],
        boolean
      ]): string;
    }>;

    viewTxns: TypedFunctionDescription<{
      encode([_txns]: [{ dest: string; data: Arrayish }[]]): string;
    }>;
  };

  events: {
    Error: TypedEventDescription<{
      encodeTopics([tx_id, error]: [null, null]): string[];
    }>;
  };
}

export class TxnAggregator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): TxnAggregator;
  attach(addressOrName: string): TxnAggregator;
  deployed(): Promise<TxnAggregator>;

  on(event: EventFilter | string, listener: Listener): TxnAggregator;
  once(event: EventFilter | string, listener: Listener): TxnAggregator;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): TxnAggregator;
  removeAllListeners(eventName: EventFilter | string): TxnAggregator;
  removeListener(eventName: any, listener: Listener): TxnAggregator;

  interface: TxnAggregatorInterface;

  functions: {
    executeTxns(
      _txns: { dest: string; data: Arrayish }[],
      _revert: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    singleContract_executeTxns(
      _contract: string,
      _txns: Arrayish[],
      _revert: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    viewTxns(_txns: { dest: string; data: Arrayish }[]): Promise<string[]>;
  };

  executeTxns(
    _txns: { dest: string; data: Arrayish }[],
    _revert: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  singleContract_executeTxns(
    _contract: string,
    _txns: Arrayish[],
    _revert: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  viewTxns(_txns: { dest: string; data: Arrayish }[]): Promise<string[]>;

  filters: {
    Error(tx_id: null, error: null): EventFilter;
  };

  estimate: {
    executeTxns(
      _txns: { dest: string; data: Arrayish }[],
      _revert: boolean
    ): Promise<BigNumber>;

    singleContract_executeTxns(
      _contract: string,
      _txns: Arrayish[],
      _revert: boolean
    ): Promise<BigNumber>;

    viewTxns(_txns: { dest: string; data: Arrayish }[]): Promise<BigNumber>;
  };
}
