/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CallReceiverMockInterface extends ethers.utils.Interface {
  functions: {
    "lastValA()": FunctionFragment;
    "lastValB()": FunctionFragment;
    "setRevertFlag(bool)": FunctionFragment;
    "testCall(uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "lastValA", values?: undefined): string;
  encodeFunctionData(functionFragment: "lastValB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRevertFlag",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "testCall",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "lastValA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastValB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRevertFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testCall", data: BytesLike): Result;

  events: {};
}

export class CallReceiverMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CallReceiverMockInterface;

  functions: {
    lastValA(overrides?: CallOverrides): Promise<[BigNumber]>;

    "lastValA()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastValB(overrides?: CallOverrides): Promise<[string]>;

    "lastValB()"(overrides?: CallOverrides): Promise<[string]>;

    setRevertFlag(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setRevertFlag(bool)"(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCall(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "testCall(uint256,bytes)"(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  lastValA(overrides?: CallOverrides): Promise<BigNumber>;

  "lastValA()"(overrides?: CallOverrides): Promise<BigNumber>;

  lastValB(overrides?: CallOverrides): Promise<string>;

  "lastValB()"(overrides?: CallOverrides): Promise<string>;

  setRevertFlag(
    _revertFlag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setRevertFlag(bool)"(
    _revertFlag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCall(
    _valA: BigNumberish,
    _valB: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "testCall(uint256,bytes)"(
    _valA: BigNumberish,
    _valB: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    lastValA(overrides?: CallOverrides): Promise<BigNumber>;

    "lastValA()"(overrides?: CallOverrides): Promise<BigNumber>;

    lastValB(overrides?: CallOverrides): Promise<string>;

    "lastValB()"(overrides?: CallOverrides): Promise<string>;

    setRevertFlag(
      _revertFlag: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setRevertFlag(bool)"(
      _revertFlag: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    testCall(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "testCall(uint256,bytes)"(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    lastValA(overrides?: CallOverrides): Promise<BigNumber>;

    "lastValA()"(overrides?: CallOverrides): Promise<BigNumber>;

    lastValB(overrides?: CallOverrides): Promise<BigNumber>;

    "lastValB()"(overrides?: CallOverrides): Promise<BigNumber>;

    setRevertFlag(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setRevertFlag(bool)"(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCall(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "testCall(uint256,bytes)"(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    lastValA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastValA()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastValB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lastValB()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setRevertFlag(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setRevertFlag(bool)"(
      _revertFlag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCall(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "testCall(uint256,bytes)"(
      _valA: BigNumberish,
      _valB: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
